login:
  username: gcardozo
  password:

project_info:
  project: SIMBR
  team: ['adrianno', 'enio', 'newmar', 'bruno', 'darci', 'gcardozo']

tasks_info:
  startdate: 2018-12-26
  enddate: 2019-03-25
  resolutions: ['Fixed', 'Done']